// packages/vue/src/VeniaProvider.vue
<script setup lang="ts">
import { ref, shallowRef, provide, onMounted, onUnmounted } from 'vue'
import { ConsentStore, initScriptGate } from '@venia-consent/core'
import type { VeniaConfig, ConsentState } from '@venia-consent/core'
import { VeniaKey } from './useConsent'
import ConsentComponent from './components/ConsentComponent.vue'

const props = withDefaults(
  defineProps<{ config: VeniaConfig; mode?: 'banner' | 'card' | 'modal' }>(),
  { mode: 'banner' },
)

const store = shallowRef<ConsentStore | null>(null)
const consent = ref<ConsentState | null>(null)
let unsubscribe: (() => void) | null = null

onMounted(async () => {
  const s = await ConsentStore.create(props.config)
  store.value = s
  consent.value = s.getConsent()
  initScriptGate(s)
  unsubscribe = s.onChange((state) => {
    consent.value = state
  })
})

onUnmounted(() => unsubscribe?.())

provide(VeniaKey, {
  get store() {
    if (!store.value) throw new Error('Venia store not yet initialized')
    return store.value
  },
  consent,
} as unknown as { store: ConsentStore; consent: typeof consent })
</script>

<template>
  <slot />
  <ConsentComponent v-if="store" :store="store" :mode="mode" />
</template>

// packages/react/src/VeniaProvider.tsx
'use client'

import { createContext, useEffect, useState, useMemo } from 'react'

import { ConsentStore, initScriptGate } from '@venia/core'
import type { VeniaConfig, ConsentState } from '@venia/core'

import { ConsentComponent } from './components/ConsentComponent'

export const VeniaContext = createContext<{
  store: ConsentStore
  consent: ConsentState | null
} | null>(null)

export function VeniaProvider({
  config,
  children,
  mode = 'banner',
}: {
  config?: VeniaConfig
  children: React.ReactNode
  mode?: 'banner' | 'card' | 'modal'
}) {
  const store = useMemo(() => new ConsentStore(config), [config])
  const [consent, setConsent] = useState(store.getConsent())

  useEffect(() => {
    initScriptGate(store)
    const unsubscribe = store.onChange(setConsent)
    return () => {
      unsubscribe()
    }
  }, [store])

  const value = useMemo(() => ({ store, consent }), [store, consent])

  return (
    <VeniaContext.Provider value={value}>
      {children}
      <ConsentComponent store={store} mode={mode} />
    </VeniaContext.Provider>
  )
}
