// packages/vue/src/components/ConsentCard.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import type { ConsentStore } from '@venia-consent/core'

import ConsentCategoryList from './ConsentCategoryList.vue'
import { useConsentCategories } from '../useConsentCategories'

const props = defineProps<{ store: ConsentStore }>()
const { categories, selected, toggle, save } = useConsentCategories(props.store)
const customizeVisible = ref(false)
const config = computed(() => props.store.getConfig())

const toggleCustomize = () => {
  customizeVisible.value = !customizeVisible.value
}

const rejectAll = () => props.store.rejectAll()
const acceptAll = () => props.store.acceptAll()
const savePreferences = () => save()
</script>

<template>
  <div class="venia-card" role="dialog" aria-label="Cookie consent">
    <h2 class="venia-heading">
      {{ config.bannerHeading ?? 'This site uses cookies' }}
    </h2>
    <p class="venia-content">
      {{
        config.bannerText ??
        'We use cookies to enhance your experience. By continuing to visit this site you agree to our use of cookies.'
      }}
    </p>

    <div v-if="customizeVisible" class="venia-customize venia-customize--compact">
      <ConsentCategoryList
        :categories="categories"
        :selected="selected"
        :on-toggle="toggle"
        compact
      />
    </div>

    <div class="venia-actions">
      <button class="venia-btn" @click="rejectAll">Reject all</button>
      <button class="venia-btn" @click="acceptAll">Accept all</button>
      <button class="venia-btn venia-btn--ghost" @click="toggleCustomize">
        {{ customizeVisible ? 'Hide' : 'Customize' }}
      </button>
      <button
        v-if="customizeVisible"
        class="venia-btn venia-btn--ghost venia-btn--save"
        @click="savePreferences"
      >
        Save
      </button>
    </div>
  </div>
</template>

// packages/react/src/components/ConsentCard.tsx
'use client'

import { useState } from 'react'

import type { ConsentStore } from '@venia/core'

import { ConsentCategoryList } from './ConsentCategoryList'
import { useConsentCategories } from '../useConsentCategories'

export function ConsentCard({ store }: { store: ConsentStore }) {
  const { categories, selected, toggle, save } = useConsentCategories(store)
  const [customizeVisible, setCustomizeVisible] = useState(false)

  return (
    <div className="venia-card" role="dialog" aria-label="Cookie consent">
      <h2 className="venia-heading">
        {store.getConfig().bannerHeading ?? 'This site uses cookies'}
      </h2>
      <p className="venia-content">
        {store.getConfig().bannerText ??
          'We use cookies to enhance your experience. By continuing to visit this site you agree to our use of cookies.'}
      </p>

      {customizeVisible && (
        <div className="venia-customize venia-customize--compact">
          <ConsentCategoryList
            categories={categories}
            selected={selected}
            onToggle={toggle}
            compact
          />
        </div>
      )}

      <div className="venia-actions">
        <button className="venia-btn" onClick={() => store.rejectAll()}>
          Reject all
        </button>
        <button className="venia-btn" onClick={() => store.acceptAll()}>
          Accept all
        </button>
        <button
          className="venia-btn venia-btn--ghost"
          onClick={() => setCustomizeVisible((prev) => !prev)}
        >
          {customizeVisible ? 'Hide' : 'Customize'}
        </button>
        {customizeVisible && (
          <button className="venia-btn venia-btn--ghost venia-btn--save" onClick={save}>
            Save
          </button>
        )}
      </div>
    </div>
  )
}
